image: docker:stable
services:
  - docker:dind

variables:
  DOCKER_DRIVER: overlay
  HEROKU_APP_NAME: adn-decrypt

stages:
  - deploy-dev
  - deploy-stage
  - deploy-prod

deploy-dev:
  stage: deploy-dev
  when: manual
  script:
    - apk add --no-cache curl
    - docker build --tag $HEROKU_DEV_REGISTRY --file ./Dockerfile "."
    - docker login -u $HEROKU_USER -p $HEROKU_AUTH_TOKEN registry.heroku.com
    - docker push $HEROKU_DEV_REGISTRY
    - ./deploy-dev.sh $HEROKU_DEV_REGISTRY

deploy-stage:
  stage: deploy-stage
  when: manual
  only:
    - master
  script:
    - apk add --no-cache curl
    - docker build --tag $HEROKU_STAGE_REGISTRY --file ./Dockerfile "."
    - docker login -u $HEROKU_USER -p $HEROKU_AUTH_TOKEN registry.heroku.com
    - docker push $HEROKU_STAGE_REGISTRY
    - ./deploy-stage.sh $HEROKU_STAGE_REGISTRY

deploy-prod:
  stage: deploy-prod
  when: manual
  only:
    - master
  script:
    - apk add --no-cache curl
    - docker build --tag $HEROKU_PROD_REGISTRY --file ./Dockerfile "."
    - docker login -u $HEROKU_USER -p $HEROKU_AUTH_TOKEN registry.heroku.com
    - docker push $HEROKU_PROD_REGISTRY
    - ./deploy-prod.sh $HEROKU_PROD_REGISTRY
