export const en = {
    translation: {
        // Menu items
        'menuItems.home': 'Home',
        'menuItems.dashboard': 'Dashboard',

        // Common module
        'LoaderComponent.placeholder': 'Loading',
        'DashboardPage.title': 'Dashboard',
        'AccountButtonComponent.account': 'Account',
        'AccountButtonComponent.tooltip': 'Account menu',
        'SignOutComponent.signOut': 'Sign Out',

        // Bands Module
        'AllBandsPage.title': 'All Bands',
        'CreateBandPage.title': 'Create new Band',
        'CreateBandPage.generalStep': 'General Info',
        'CreateBandPage.contentStep': 'Content',
        'CreateBandPage.imagesStep': 'Upload Images',
        'CreateBandPage.linksStep': 'Create Links',
        'CreateBandPage.contactsStep': 'Create Contacts',
        'CreateBandPage.back': 'Back',
        'CreateBandPage.skip': 'Skip',
        'CreateBandPage.next': 'Next',
        'CreateBandPage.name': 'Name',
        'CreateBandPage.url': 'Path',
        'BandProfilePage.defaultTitle': '...Loading',
        'BandProfilePage.errorTitle': 'Not Found',
        'ManageBandProfilePage.defaultTitle': '...Loading',
        'ManageBandProfilePage.errorTitle': 'Not Found',
        'ManageBandProfilePage.viewMode': 'View Mode',
        'ManageBandProfilePage.menu.profile': 'Profile',
        'ManageBandProfilePage.menu.content': 'Content',
        'ManageBandProfilePage.menu.links': 'Links',
        'ManageBandProfilePage.menu.contacts': 'Contacts',
        'ManageBandProfilePage.menu.images': 'Images',
        'ManageBandProfileComponent.manage': 'Manage',
        'ManageBandProfileComponent.content': 'Content',
        'ManageBandProfileComponent.profile': 'Profile',
        'ManageBandProfileComponent.links': 'Links',
        'ManageBandProfileComponent.contacts': 'Contacts',
        'ManageBandProfilePage.menu.settings': 'Settings',
        'UpdateBandComponent.name': 'Name',
        'UpdateBandComponent.url': 'Path',
        'UpdateBandComponent.discard': 'Discard',
        'UpdateBandComponent.save': 'Save',
        'BandNotFoundComponent.placeholder': 'Not found :(',
        'BandsSearchBarComponent.search': 'Search',
        'BandStatsComponent.bandsCount': 'Bands Count',
        'PopularBandsComponent.title': 'Most Popular',
        'PopularBandsComponent.viewMore': 'View More',
        'RecentBandsComponent.title': 'Recent',
        'RecentBandsComponent.viewMore': 'View More',
        'MyBandsComponent.title': 'My Bands',
        'MyBandsComponent.create': 'Create',

        // Links module
        'LinksListComponent.emptyPlaceholder': 'No Links...',
        'LinksListComponent.links': 'Links',
        'ManageLinksComponent.emptyPlaceholder': 'No Links... Please, create a first one.',
        'CreateLinkComponent.title': 'New Link',
        'CreateLinkComponent.name': 'Name',
        'CreateLinkComponent.description': 'Description',
        'CreateLinkComponent.value': 'Link',
        'CreateLinkComponent.type': 'Type',
        'CreateLinkComponent.isPublic': 'Is Public',
        'CreateLinkComponent.create': 'Create',
        'UpdateLinkComponent.name': 'Name',
        'UpdateLinkComponent.description': 'Description',
        'UpdateLinkComponent.value': 'Link',
        'UpdateLinkComponent.type': 'Type',
        'UpdateLinkComponent.isPublic': 'Is Public',
        'UpdateLinkComponent.delete': 'Delete',
        'UpdateLinkComponent.discard': 'Discard',
        'UpdateLinkComponent.save': 'Save',

        // Contacts module
        'ContactsListComponent.emptyPlaceholder': 'No Contacts...',
        'ContactsListComponent.contacts': 'Contacts',
        'ManageContactsComponent.emptyPlaceholder': 'No Contacts... Please, create a first one.',
        'CreateContactComponent.title': 'New Contact',
        'CreateContactComponent.name': 'Name',
        'CreateContactComponent.description': 'Description',
        'CreateContactComponent.value': 'Contact',
        'CreateContactComponent.type': 'Type',
        'CreateContactComponent.isPublic': 'Is Public',
        'CreateContactComponent.create': 'Create',
        'UpdateContactComponent.name': 'Name',
        'UpdateContactComponent.description': 'Description',
        'UpdateContactComponent.value': 'Contact',
        'UpdateContactComponent.type': 'Type',
        'UpdateContactComponent.isPublic': 'Is Public',
        'UpdateContactComponent.delete': 'Delete',
        'UpdateContactComponent.discard': 'Discard',
        'UpdateContactComponent.save': 'Save',

        // Content module
        'ManageContentComponent.emptyPlaceholder': 'Please, create a first content.',
        'ContentListComponent.emptyPlaceholder': 'Content is empty...',
        'ContentListComponent.bio': 'Biography',
        'ContentListComponent.history': 'History',
        'CreateContentComponent.create': 'Create',
        'CreateContentComponent.title': 'New Content',
        'CreateContentComponent.type': 'Content Type',
        'CreateContentComponent.locale': 'Content Language',
        'CreateContentComponent.data': 'Content',
        'CreateContentComponent.close': 'Close',
        'CreateContentComponent.save': 'Create',

        // Images module
        'GalleryComponent.emptyPlaceholder': 'Gallery is empty...',
        'ManageImagesComponent.profileImage': 'Avatar',
        'ManageImagesComponent.galleryImages': 'Gallery',

        // Members module
        'MembersListComponent.emptyPlaceholder': 'No members...',
        'MembersListComponent.members': 'Members',
        'MemberRole.Singer': 'Singer',
        'MemberRole.Guitarist': 'Guitarist',
        'MemberRole.Bassist': 'Bassist',
        'MemberRole.KeyboardPlayer': 'Keyboard Player',
        'MemberRole.Drummer': 'Drummer',
        'MemberRole.Other': 'Other',

        // Auth Module
        'AccountPage.title': 'Account',
        'SignInPage.title': 'Sign in',
        'SignInPage.signIn': 'Sign in',
        'SignInPage.email': 'Email Address',
        'SignInPage.password': 'Password',
        'SignInPage.rememberMe': 'Remember me',
        'SignInPage.forgotPassword': 'Forgot password?',
        'SignInPage.dontHaveAccount': 'Don\'t have an account? Sign Up',
        'SignUpPage.title': 'Sign Up',
        'SignUpPage.signUp': 'Sign Up',
        'SignUpPage.firstName': 'First Name',
        'SignUpPage.lastName': 'Last Name',
        'SignUpPage.email': 'Email Address',
        'SignUpPage.password': 'Password',
        'SignUpPage.hasAccount': 'Already have an account? Sign In',
        'ForgotPasswordPage.title': 'Forgot Password',
        'ForgotPasswordPage.forgotPassword': 'Forgot Password',
        'ForgotPasswordPage.description': 'Lost your password? Please enter your username or email address. You will receive a link to create a new password via email.',
        'ForgotPasswordPage.email': 'Email Address',
        'ForgotPasswordPage.resetPassword': 'Reset Password',
        'ForgotPasswordPage.rememberPassword': 'Remember your password?',
        'RestorePasswordPage.title': 'Restore Password',
        'RestorePasswordPage.restorePassword': 'Restore Password',
        'RestorePasswordPage.email': 'Email Address',
        'RestorePasswordPage.newPassword': 'New Password',
        'RestorePasswordPage.resetPassword': 'Reset Password',
        'RestorePasswordPage.rememberPassword': 'Remember your password?',
        'ChangePasswordComponent.changePassword': 'Change Password',
        'ChangePasswordComponent.oldPassword': 'Old Password',
        'ChangePasswordComponent.newPassword': 'New Password',
        'ChangePasswordComponent.submit': 'Change',
        'UpdateIdentityComponent.updateIdentity': 'Update Profile',
        'UpdateIdentityComponent.firstName': 'First Name',
        'UpdateIdentityComponent.lastName': 'LastName',
        'UpdateIdentityComponent.locale': 'Locale',
        'UpdateIdentityComponent.discard': 'Discard',
        'UpdateIdentityComponent.submit': 'Update'
    }
};