export const ua = {
    translation: {
        // Menu items
        'menuItems.home': 'Головна',
        'menuItems.dashboard': 'Панель',

        // Common module
        'LoaderComponent.placeholder': 'Завантаження',
        'AccountButtonComponent.account': 'Профіль',
        'AccountButtonComponent.tooltip': 'Меню профілю',
        'SignOutComponent.signOut': 'Вийти',
        'DashboardPage.title': 'Дешборд',

        // Bands Module
        'AllBandsPage.title': 'Всі Гурти',
        'CreateBandPage.title': 'Новий Гурт',
        'CreateBandPage.generalStep': 'Загальна інформація',
        'CreateBandPage.contentStep': 'Опис',
        'CreateBandPage.imagesStep': 'Завантажте зображення',
        'CreateBandPage.linksStep': 'Створити посилання',
        'CreateBandPage.contactsStep': 'Створити контакти',
        'CreateBandPage.back': 'Назад',
        'CreateBandPage.skip': 'Пропустити',
        'CreateBandPage.next': 'Вперед',
        'CreateBandPage.name': 'Назва',
        'CreateBandPage.url': 'Шлях',
        'BandProfilePage.defaultTitle': '...Завантаження',
        'BandProfilePage.errorTitle': 'Не Знайдено',
        'ManageBandProfilePage.defaultTitle': '...Завантаження',
        'ManageBandProfilePage.errorTitle': 'Не Знайдено',
        'ManageBandProfilePage.viewMode': 'Перегляд',
        'ManageBandProfilePage.menu.profile': 'Порофіль',
        'ManageBandProfilePage.menu.content': 'Контент',
        'ManageBandProfilePage.menu.links': 'Посилання',
        'ManageBandProfilePage.menu.contacts': 'Контакти',
        'ManageBandProfilePage.menu.images': 'зображення',
        'ManageBandProfileComponent.manage': 'Управління',
        'ManageBandProfileComponent.content': 'Контент',
        'ManageBandProfileComponent.profile': 'Профіль ',
        'ManageBandProfileComponent.links': 'Посилання',
        'ManageBandProfileComponent.contacts': 'Контакти',
        'ManageBandProfilePage.menu.settings': 'Налаштування',
        'UpdateBandComponent.name': 'Назва',
        'UpdateBandComponent.url': 'Шлях',
        'UpdateBandComponent.discard': 'Відмінити',
        'UpdateBandComponent.save': 'Зберегти',
        'BandNotFoundComponent.placeholder': 'Нічого не знайдено :(',
        'BandsListComponent.viewMore': 'Дивитись Більше',
        'BandsSearchBarComponent.search': 'Пошук',
        'BandStatsComponent.bandsCount': 'Кількість Груп',
        'PopularBandsComponent.title': 'Найпопулярніші',
        'PopularBandsComponent.viewMore': 'Дивитись Більше',
        'RecentBandsComponent.title': 'Нещодавні',
        'RecentBandsComponent.viewMore': 'Дивитись Більше',
        'MyBandsComponent.title': 'Мої Гурти',
        'MyBandsComponent.create': 'Створити',

        // Links module
        'LinksListComponent.emptyPlaceholder': 'Немає посилань...',
        'LinksListComponent.links': 'Посилання',
        'ManageLinksComponent.emptyPlaceholder': 'Немає посілань... Створіть ваше перше посилання.',
        'CreateLinkComponent.title': 'Нове посилання',
        'CreateLinkComponent.name': 'Назва',
        'CreateLinkComponent.description': 'Опис',
        'CreateLinkComponent.value': 'Посилання',
        'CreateLinkComponent.type': 'Тип',
        'CreateLinkComponent.isPublic': 'Чи публічне',
        'CreateLinkComponent.create': 'Створити',
        'UpdateLinkComponent.name': 'Назва',
        'UpdateLinkComponent.description': 'Опис',
        'UpdateLinkComponent.value': 'Посилання',
        'UpdateLinkComponent.type': 'Тип',
        'UpdateLinkComponent.isPublic': 'Чи публічне',
        'UpdateLinkComponent.delete': 'Видалити',
        'UpdateLinkComponent.discard': 'Скасувати',
        'UpdateLinkComponent.save': 'Зберегти',

        // Contacts module
        'ContactsListComponent.emptyPlaceholder': 'Немає контактів...',
        'ContactsListComponent.contacts': 'Контакти',
        'ManageContactsComponent.emptyPlaceholder': 'Немає контактів... Створіть ваш перший контакт.',
        'CreateContactComponent.title': 'Новий контакт',
        'CreateContactComponent.name': 'Назва',
        'CreateContactComponent.description': 'Опис',
        'CreateContactComponent.value': 'Контакт',
        'CreateContactComponent.type': 'Тип',
        'CreateContactComponent.isPublic': 'Чи публічне',
        'CreateContactComponent.create': 'Створити',
        'UpdateContactComponent.name': 'Назва',
        'UpdateContactComponent.description': 'Опис',
        'UpdateContactComponent.value': 'Контакт',
        'UpdateContactComponent.type': 'Тип',
        'UpdateContactComponent.isPublic': 'Чи публічне',
        'UpdateContactComponent.delete': 'Видалити',
        'UpdateContactComponent.discard': 'Скасувати',
        'UpdateContactComponent.save': 'Зберегти',

        // Content module
        'ManageContentComponent.emptyPlaceholder': 'Створіть ваш перший контент.',
        'ContentListComponent.emptyPlaceholder': 'Контен відсутній...',
        'ContentListComponent.bio': 'Біографія',
        'ContentListComponent.history': 'Історія',
        'CreateContentComponent.create': 'Створити',
        'CreateContentComponent.title': 'Новий контент',
        'CreateContentComponent.type': 'Тип контенту Type',
        'CreateContentComponent.locale': 'Мова контенту',
        'CreateContentComponent.data': 'Контент',
        'CreateContentComponent.close': 'Закрити',
        'CreateContentComponent.save': 'Створити',

        // Images module
        'GalleryComponent.emptyPlaceholder': 'В галереї пусто...',
        'ManageImagesComponent.profileImage': 'Аватар',
        'ManageImagesComponent.galleryImages': 'Галерея',

        // Members module
        'MembersListComponent.emptyPlaceholder': 'Немає учасників...',
        'MembersListComponent.members': 'Учасники',
        'MemberRole.Singer': 'Співак',
        'MemberRole.Guitarist': 'Гітарист',
        'MemberRole.Bassist': 'Басист',
        'MemberRole.KeyboardPlayer': 'Клавішник',
        'MemberRole.Drummer': 'Барабанщик',
        'MemberRole.Other': 'Іншне',

        // Auth Module
        'AccountPage.title': 'Профіль',
        'SignInPage.title': 'Авторизація',
        'SignInPage.signIn': 'Авторизація',
        'SignInPage.email': 'Електронна Адреса',
        'SignInPage.password': 'Пароль',
        'SignInPage.rememberMe': 'Запамʼятати мене',
        'SignInPage.forgotPassword': 'Забули пароль?',
        'SignInPage.dontHaveAccount': 'Не маєте акаунту? Зареєструватись',
        'SignUpPage.title': 'Реєстрація',
        'SignUpPage.signUp': 'Реєстрація',
        'SignUpPage.firstName': 'Імʼя',
        'SignUpPage.lastName': 'Прізвище',
        'SignUpPage.email': 'Електронна Адреса',
        'SignUpPage.password': 'Пароль',
        'SignUpPage.hasAccount': 'Вже зареєстровані? Увійти',
        'ForgotPasswordPage.title': 'Забули пароль',
        'ForgotPasswordPage.forgotPassword': 'Забули пароль',
        'ForgotPasswordPage.description': 'Забули пароль? Будь ласка, введіть своє імʼя користувача або адресу електронної пошти. Ви отримаєте посилання для створення нового пароля на електронну пошту.',
        'ForgotPasswordPage.email': 'Електронна Адреса',
        'ForgotPasswordPage.resetPassword': 'Відновити Пароль',
        'ForgotPasswordPage.rememberPassword': 'Памʼятаєте пароль?',
        'RestorePasswordPage.title': 'Відновлення Паролю',
        'RestorePasswordPage.restorePassword': 'Відновлення Паролю',
        'RestorePasswordPage.email': 'Електронна Адреса',
        'RestorePasswordPage.newPassword': 'Новий Пароль',
        'RestorePasswordPage.resetPassword': 'Відновити Пароль',
        'RestorePasswordPage.rememberPassword': 'Памʼятаєте пароль?',
        'ChangePasswordComponent.changePassword': 'Змінити пароль',
        'ChangePasswordComponent.oldPassword': 'Старий пароль',
        'ChangePasswordComponent.newPassword': 'Новий пароль',
        'ChangePasswordComponent.submit': 'Змінити',
        'UpdateIdentityComponent.updateIdentity': 'Редагувати Профіль',
        'UpdateIdentityComponent.firstName': 'Імʼя',
        'UpdateIdentityComponent.lastName': 'Прізвище',
        'UpdateIdentityComponent.locale': 'Локалізація',
        'UpdateIdentityComponent.discard': 'Відмінити',
        'UpdateIdentityComponent.submit': 'Зберегти'
    }
}